### ISSUE TITLE
about the best model

### ISSUE THREAD

**Issue by qjianying** [YijinHuang/Lesion-based-Contrastive-Learning#1]
hello, can you tell me how to load your best model?

**Comment by YijinHuang** [comment]
Hi. Sorry for confusing you. We have added the [example codes](https://github.com/YijinHuang/Lesion-based-Contrastive-Learning#load-trained-models) in README. We also updated the models in the release, please remember to download them again. If there is any problem, please feel free to comment here. Thank you.

**Comment by qjianying** [comment]
dear YijinHuang:
&nbsp; &nbsp; &nbsp; Thank you very much.&nbsp;
&nbsp; &nbsp; &nbsp; I'm sorry to bother you again. I have another question to ask you. Why is the output of the network full connection layer 2 instead of the category number 5?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YijinHuang/Lesion-based-Contrastive-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YijinHuang/Lesion-based-Contrastive-Learning] about the best model (Issue #1)





 
Hi. Sorry for confusing you. We have added the example codes in README. We also updated the models in the release, please remember to download them again. If there is any problem, please feel free to comment here. Thank you.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YijinHuang** [comment]
Because in this work, we treat the task of DR classification as a regression task. The softmax layer of the fully connected layer is removed and the output dimension is set to be 1 to produce a prediction score. In the testing phase, the prediction score is clipped to be between [0, 4] and then simply rounded to integers to serve as the final predicted grade. You can find more details in section 3.2.4 of our other preprinted paper (https://arxiv.org/pdf/2110.14160.pdf).

**Comment by qjianying** [comment]
Dear YijinHuang:


&nbsp; &nbsp; &nbsp; Thank you very much. I feel very honored that you can take the time to answer for me. I have understood, and I have no other questions for the moment. Thank you again.




&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Best wishes!

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; qjianying




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YijinHuang/Lesion-based-Contrastive-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YijinHuang/Lesion-based-Contrastive-Learning] about the best model (Issue #1)





 
Because in this work, we treat the task of DR classification as a regression task. The softmax layer of the fully connected layer is removed and the output dimension is set to be 1 to produce a prediction score. In the testing phase, the prediction score is clipped to be between [0, 4] and then simply rounded to integers to serve as the final predicted grade. You can find more details in section 3.2.4 of our other preprinted paper (https://arxiv.org/pdf/2110.14160.pdf).
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YijinHuang** [comment]
You're welcome. Thank you for your interest.
