### ISSUE TITLE
I want to use detection model from scratch . But I got error about mmcv module. What is the version you used?

### ISSUE THREAD

**Issue by osivaz61** [YijinHuang/Lesion-based-Contrastive-Learning#5]

**Comment by osivaz61** [comment]
Also what is the mmdet module version you used?

**Comment by YijinHuang** [comment]
The versions of mmcv and mmdet I used were 1.2.6 and 2.8.0, respectively. However, these versions are outdated. I recommend upgrading to the latest version of mmdetection to achieve better detection performance.

**Comment by osivaz61** [comment]
Thanks a lot.
