### ISSUE TITLE
Detection procedure...

### ISSUE THREAD

**Issue by osivaz61** [YijinHuang/Lesion-based-Contrastive-Learning#8]
I want to ask some questions about detection. Fistly I need to convert masks to bounding boxes for every lesion and get .csv file for every lesion? Am I right? For every lesion I should run mask2bbox.py?

**Comment by YijinHuang** [comment]
Yes, you are right. The conversion was necessary in this work because the dataset employed only contained segmentation annotations. If you are using a dataset having bounding box annotations, then you can skip this procedure.

**Comment by osivaz61** [comment]
After that, should I merge CSV files and give the merged file to csv2coco.py?
